### ISSUE TITLE
Feature request: grep for certain variables - Awesome list of secrets in environment variables

### ISSUE THREAD

**Issue by nitram2342** [floyd-fuh/crass#3]
Dear Tobias,

@Puliczek collects a list of secrets, passwords, API keys, tokens stored inside a system environment variables, which could be integrated into `crass`:

https://github.com/Puliczek/awesome-list-of-secrets-in-environment-variables

**Comment by floyd-fuh** [comment]
Done, see commit https://github.com/floyd-fuh/crass/commit/edd1f2674b33d16f8d7a505f75bdc52f6eaee8a8
